# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

EigenR_det_real <- function(M) {
    .Call('_EigenR_EigenR_det_real', PACKAGE = 'EigenR', M)
}

EigenR_det_cplx <- function(Re, Im) {
    .Call('_EigenR_EigenR_det_cplx', PACKAGE = 'EigenR', Re, Im)
}

