# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

EigenR_det_real <- function(M) {
    .Call('_EigenR_EigenR_det_real', PACKAGE = 'EigenR', M)
}

EigenR_det_cplx <- function(Re, Im) {
    .Call('_EigenR_EigenR_det_cplx', PACKAGE = 'EigenR', Re, Im)
}

EigenR_rank_real <- function(M) {
    .Call('_EigenR_EigenR_rank_real', PACKAGE = 'EigenR', M)
}

EigenR_rank_cplx <- function(Re, Im) {
    .Call('_EigenR_EigenR_rank_cplx', PACKAGE = 'EigenR', Re, Im)
}

EigenR_kernel_COD_real <- function(M) {
    .Call('_EigenR_EigenR_kernel_COD_real', PACKAGE = 'EigenR', M)
}

EigenR_kernel_COD_cplx <- function(Re, Im) {
    .Call('_EigenR_EigenR_kernel_COD_cplx', PACKAGE = 'EigenR', Re, Im)
}

EigenR_kernel_LU_real <- function(M) {
    .Call('_EigenR_EigenR_kernel_LU_real', PACKAGE = 'EigenR', M)
}

EigenR_kernel_LU_cplx <- function(Re, Im) {
    .Call('_EigenR_EigenR_kernel_LU_cplx', PACKAGE = 'EigenR', Re, Im)
}

EigenR_image_LU_real <- function(M) {
    .Call('_EigenR_EigenR_image_LU_real', PACKAGE = 'EigenR', M)
}

EigenR_image_LU_cplx <- function(Re, Im) {
    .Call('_EigenR_EigenR_image_LU_cplx', PACKAGE = 'EigenR', Re, Im)
}

EigenR_image_QR_real <- function(M) {
    .Call('_EigenR_EigenR_image_QR_real', PACKAGE = 'EigenR', M)
}

EigenR_image_QR_cplx <- function(Re, Im) {
    .Call('_EigenR_EigenR_image_QR_cplx', PACKAGE = 'EigenR', Re, Im)
}

